services:
  db:
    image: clash-db
    container_name: clash-db
    volumes: 
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cron:
    build: ./cron
    image: clash-cron
    container_name: clash-cron
    depends_on:
      - db
    environment:
      - TOK
  backend:
    build: ./backend
    image: clash-backend
    container_name: clash-backend
    depends_on:
      - db
    environment:
      - TOK
  frontend:
    build: ./frontend
    image: clash-frontend
    container_name: clash-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
