services:
  db:
    image: clash-db
    container_name: clash-db
    volumes: 
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cron:
    image: clash-cron
    container_name: clash-cron
    depends_on:
      - db
