CREATE TABLE IF NOT EXISTS userinfo (
  id SERIAL PRIMARY KEY, playertag VARCHAR(15) NOT NULL, phonenumber VARCHAR(10) NOT NULL, passwd VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS playerwarattacks (
  id SERIAL PRIMARY KEY, playertag VARCHAR(15) NOT NULL, clantag VARCHAR(15) NOT NULL, time TIMESTAMP NOT NULL, defendertag VARCHAR(15) NOT NULL, stars VARCHAR(1), destructionpercentage VARCHAR(5), theorder VARCHAR(5), duration VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS clanwars (
  id SERIAL PRIMARY KEY, clantag VARCHAR(15) NOT NULL, time TIMESTAMP NOT NULL, clanwardata VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS playerhistory (
  id SERIAL PRIMARY KEY, time TIMESTAMP NOT NULL, playertag VARCHAR(15) NOT NULL, playerdata VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS clanhistory (
  id SERIAL PRIMARY KEY, time TIMESTAMP NOT NULL, clantag VARCHAR(15) NOT NULL, clandata VARCHAR(255) NOT NULL
);
