name: Db Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  restart-compose:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: |
        source $HOME/.bashrc
        cd /home/bob/clash-dashboard/frontend/clash-frontend/src
        npm run build
        cd /home/bob/clash-dashboard
        bash start.sh
