name: Cron Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cron/**'
jobs:

  cron-job:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd /home/bob/clash-dashboard/cron
        docker build . -f Dockerfile.cron -t clash-cron
