name: Db Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  restart-compose:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: |
        docker-compose build
        docker-compose up -d
