name: Cron Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cron/**'
jobs:

  cron-job:
    if: contains(join(github.event.commits.*.modified), 'cron/')
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd /home/bob/clash-dashboard 
        docker build . -f Dockerfile.cron -t clash-cron
  db-job:
    if: contains(join(github.event.commits.*.modified), 'db/')
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd /home/bob/clash-dashboard 
        docker build . -f Dockerfile.cron -t clash-db
